---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: btp-ckt
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: eg 
  circuitBreaker:
    maxConnections: 40