---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: ngx-tcp-health
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: ngx-route
  healthCheck:
    active:
      type: TCP
      tcp: {} #empty payload trigger connect-only (half open)
      interval: 5s
      timeout: 1s
      unhealthyThreshold: 3
      healthyThreshold: 1
