apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: ngx-health
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: ngx-route
  healthCheck:
    active:
      type: HTTP
      http:
        path: /
        method: GET 
        expectedStatuses:
          - 404
      interval: 5s
      timeout: 1s
      unhealthyThreshold: 3
      healthyThreshold: 1
